using EllieMae.Encompass.BusinessObjects.Loans;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace FormPlugin
{
   
        public class _1008___TSUM_P1CLASS
        {
            public NameValueCollection RunScript(Loan loan)
            {
                NameValueCollection nameValueCollection = new NameValueCollection();
                string str1 = string.Empty;
                string str2 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
                nameValueCollection.Add("36_37", str2);
                string str3 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
                nameValueCollection.Add("68_69", str3);
                string str4 = JS.GetStr(loan, "65");
                nameValueCollection.Add("65", str4);
                string str5 = JS.GetStr(loan, "97");
                nameValueCollection.Add("97", str5);
                string str6 = JS.GetStr(loan, "11") + "  " + JS.GetStr(loan, "12") + Jed.BF(String.Compare(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
                nameValueCollection.Add("11_12_14", str6);
                string str7 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "1 Unit", false) == 0, "X");
                nameValueCollection.Add("1553_1unit", str7);
                string str8 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "2-4 Units", false) == 0, "X");
                nameValueCollection.Add("1553_2_4_unit", str8);
                string str9 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "Cooperative", false) == 0, "X");
                nameValueCollection.Add("1553_Co_op", str9);
                string str10 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "Condominium", false) == 0, "X");
                nameValueCollection.Add("1553_Cond", str10);
                string str11 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "PUD", false) == 0, "X");
                nameValueCollection.Add("1553_PUD", str11);
                string str12 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "Manufactured Housing Multiwide", false) == 0 | String.Compare(JS.GetStr(loan, "1553"), "Manufactured Housing Single Wide", false) == 0, "X");
                nameValueCollection.Add("1553_Manu", str12);
                string str13 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "Manufactured Housing Multiwide", false) == 0, "X");
                nameValueCollection.Add("1553_Multi", str13);
                string str14 = Jed.BF(String.Compare(JS.GetStr(loan, "1553"), "Manufactured Housing Single Wide", false) == 0, "X");
                nameValueCollection.Add("1553_Single", str14);
                string str15 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "A_IIICondominium", false) == 0, "X");
                nameValueCollection.Add("1012_A/III", str15);
                string str16 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "B_IICondominium", false) == 0, "X");
                nameValueCollection.Add("1012_B/II", str16);
                string str17 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "C_ICondominium", false) == 0, "X");
                nameValueCollection.Add("1012_C/I", str17);
                string str18 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "E_PUD", false) == 0, "X");
                nameValueCollection.Add("1012_E", str18);
                string str19 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "F_PUD", false) == 0, "X");
                nameValueCollection.Add("1012_F", str19);
                string str20 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "T_PUD", false) == 0, "X");
                nameValueCollection.Add("1012_TPUD", str20);
                string str21 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "OneCooperative", false) == 0, "X");
                nameValueCollection.Add("1012_1", str21);
                string str22 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "TwoCooperative", false) == 0, "X");
                nameValueCollection.Add("1012_2", str22);
                string str23 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "TCooperative", false) == 0, "X");
                nameValueCollection.Add("1012_TCOOP", str23);
                string str24 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "P_LimitedReviewNew", false) == 0, "X");
                nameValueCollection.Add("1012_P", str24);
                string str25 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "Q_LimitedReviewEst", false) == 0, "X");
                nameValueCollection.Add("1012_Q", str25);
                string str26 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "R_ExpeditedNew", false) == 0, "X");
                nameValueCollection.Add("1012_R", str26);
                string str27 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "S_ExpeditedEst", false) == 0, "X");
                nameValueCollection.Add("1012_S", str27);
                string str28 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "T_FannieMaeReview", false) == 0, "X");
                nameValueCollection.Add("1012_T", str28);
                string str29 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "U_FHAapproved", false) == 0, "X");
                nameValueCollection.Add("1012_U", str29);
                string str30 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "V_RefiPlus", false) == 0, "X");
                nameValueCollection.Add("1012_V", str30);
                string str31 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "DetachedProject", false) == 0, "X");
                nameValueCollection.Add("1012_DP", str31);
                string str32 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "2To4UnitProject", false) == 0, "X");
                nameValueCollection.Add("1012_24U", str32);
                string str33 = Jed.BF(String.Compare(JS.GetStr(loan, "1012"), "ReciprocalReview", false) == 0, "X");
                nameValueCollection.Add("1012_RR", str33);
                string str34 = Jed.BF(String.Compare(JS.GetStr(loan, "1811"), "PrimaryResidence", false) == 0, "X");
                nameValueCollection.Add("190_Primary", str34);
                string str35 = Jed.BF(String.Compare(JS.GetStr(loan, "1811"), "SecondHome", false) == 0, "X");
                nameValueCollection.Add("190_Second", str35);
                string str36 = Jed.BF(String.Compare(JS.GetStr(loan, "1811"), "Investor", false) == 0, "X");
                nameValueCollection.Add("190_Investment", str36);
                string str37 = JS.GetStr(loan, "16");
                nameValueCollection.Add("16", str37);
                string str38 = JS.GetStr(loan, "136");
                nameValueCollection.Add("136", str38);
                string str39 = Jed.NF(Jed.Num(JS.GetNum(loan, "356")), (byte)18, 0);
                nameValueCollection.Add("356", str39);
                string str40 = JS.GetStr(loan, "1298");
                nameValueCollection.Add("1298", str40);
                string str41 = JS.GetStr(loan, "3050");
                nameValueCollection.Add("3050", str41);
                string str42 = Jed.BF(String.Compare(JS.GetStr(loan, "1066"), "FeeSimple", false) == 0, "X");
                nameValueCollection.Add("1066_Fee", str42);
                string str43 = Jed.BF(String.Compare(JS.GetStr(loan, "1066"), "Leasehold", false) == 0, "X");
                nameValueCollection.Add("1066_Leasehold", str43);
                string str44 = Jed.BF(String.Compare(JS.GetStr(loan, "1172"), "Conventional", false) == 0, "X");
                nameValueCollection.Add("1172_Conv", str44);
                string str45 = Jed.BF(String.Compare(JS.GetStr(loan, "1172"), "FHA", false) == 0, "X");
                nameValueCollection.Add("1172_FHA", str45);
                string str46 = Jed.BF(String.Compare(JS.GetStr(loan, "1172"), "VA", false) == 0, "X");
                nameValueCollection.Add("1172_VA", str46);
                string str47 = Jed.BF(String.Compare(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, "X");
                nameValueCollection.Add("1172_USDA", str47);
                string str48 = Jed.BF(String.Compare(JS.GetStr(loan, "608"), "Fixed", false) == 0 & String.Compare(JS.GetStr(loan, "423"), "Biweekly", false) != 0, "X");
                nameValueCollection.Add("608_FixedMonthly", str48);
                string str49 = Jed.BF(String.Compare(JS.GetStr(loan, "608"), "Fixed", false) == 0 & String.Compare(JS.GetStr(loan, "423"), "Biweekly", false) == 0, "X");
                nameValueCollection.Add("608_FixedBiWeek", str49);
                string str50 = Jed.BF(String.Compare(JS.GetStr(loan, "1659"), "Y", false) == 0, "X");
                nameValueCollection.Add("608_Balloon", str50);
                string str51 = Jed.BF(String.Compare(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "X");
                nameValueCollection.Add("608_ARM", str51);
                string str52 = Jed.BF(String.Compare(JS.GetStr(loan, "608"), "OtherAmortizationType", false) == 0, "X");
                nameValueCollection.Add("608_Other", str52);
                string str53 = JS.GetStr(loan, "995");
                nameValueCollection.Add("995", str53);
                string str54 = JS.GetStr(loan, "994");
                nameValueCollection.Add("994", str54);
                string str55 = Jed.BF(String.Compare(JS.GetStr(loan, "19"), "Purchase", false) == 0, "X");
                nameValueCollection.Add("19_Purchase", str55);
                string str56 = Jed.BF(String.Compare(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 & String.Compare(JS.GetStr(loan, "299"), "CashOutHomeImprovement", false) != 0 & String.Compare(JS.GetStr(loan, "299"), "CashOutLimited", false) != 0, "X");
                nameValueCollection.Add("19_CashOut", str56);
                string str57 = Jed.BF(String.Compare(JS.GetStr(loan, "299"), "CashOutLimited", false) == 0, "X");
                nameValueCollection.Add("19_Limited", str57);
                string str58 = Jed.BF(String.Compare(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0 & String.Compare(JS.GetStr(loan, "299"), "CashOutHomeImprovement", false) != 0, "X");
                nameValueCollection.Add("19_NoCashOut", str58);
                string str59 = Jed.BF(String.Compare(JS.GetStr(loan, "299"), "CashOutHomeImprovement", false) == 0, "X");
                nameValueCollection.Add("19_Home", str59);
                string str60 = Jed.BF(String.Compare(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "X");
                nameValueCollection.Add("19_Const", str60);
                string str61 = Jed.BF(String.Compare(JS.GetStr(loan, "420"), "FirstLien", false) == 0, "X");
                nameValueCollection.Add("420_First", str61);
                string str62 = Jed.BF(String.Compare(JS.GetStr(loan, "420"), "SecondLien", false) == 0, "X");
                nameValueCollection.Add("420_Second", str62);
                string str63 = Jed.BF(String.Compare(JS.GetStr(loan, "CASASRN.X167"), "", false) != 0 & String.Compare(JS.GetStr(loan, "CASASRN.X168"), "", false) != 0, JS.GetStr(loan, "CASASRN.X167") + " / $ " + JS.GetStr(loan, "CASASRN.X168"), JS.GetStr(loan, "428"));
                nameValueCollection.Add("428", str63);
                string str64 = JS.GetStr(loan, "2");
                nameValueCollection.Add("2", str64);
                string str65 = JS.GetStr(loan, "5");
                nameValueCollection.Add("5", str65);
                string str66 = JS.GetStr(loan, "3");
                nameValueCollection.Add("3", str66);
                string str67 = JS.GetStr(loan, "4");
                nameValueCollection.Add("4", str67);
                string str68 = JS.GetStr(loan, "1557");
                nameValueCollection.Add("1557", str68);
                string str69 = Jed.BF(String.Compare(JS.GetStr(loan, "1149"), "Seller", false) == 0, "X");
                nameValueCollection.Add("1149_Seller", str69);
                string str70 = Jed.BF(String.Compare(JS.GetStr(loan, "1149"), "ThirdParty", false) == 0, "X");
                nameValueCollection.Add("1149_Broker", str70);
                string str71 = Jed.BF(String.Compare(JS.GetStr(loan, "1149"), "Correspondent", false) == 0, "X");
                nameValueCollection.Add("1149_Corres", str71);
                string str72 = JS.GetStr(loan, "1133") + Jed.BF(String.Compare(JS.GetStr(loan, "1714"), "", false) != 0, ",  ") + JS.GetStr(loan, "1714");
                nameValueCollection.Add("1133", str72);
                string str73 = Jed.BF(String.Compare(JS.GetStr(loan, "425"), "Y", false) == 0, "X");
                nameValueCollection.Add("425_Yes", str73);
                string str74 = Jed.BF(String.Compare(JS.GetStr(loan, "425"), "N", false) == 0, "X");
                nameValueCollection.Add("425_No", str74);
                string str75 = Jed.BF(String.Compare(JS.GetStr(loan, "991"), "FNM", false) == 0, "X");
                nameValueCollection.Add("991_Fannie", str75);
                string str76 = Jed.BF(String.Compare(JS.GetStr(loan, "991"), "Other", false) == 0, "X");
                nameValueCollection.Add("991_Seller", str76);
                string str77 = Jed.BF(String.Compare(JS.GetStr(loan, "991"), "FRE", false) == 0, "X");
                nameValueCollection.Add("991_Freddie", str77);
                string str78 = JS.GetStr(loan, "1085");
                nameValueCollection.Add("1085", str78);
                string str79 = JS.GetStr(loan, "984");
                nameValueCollection.Add("984", str79);
                string str80 = JS.GetStr(loan, "974");
                nameValueCollection.Add("974", str80);
                string str81 = JS.GetStr(loan, "618");
                nameValueCollection.Add("618", str81);
                string str82 = JS.GetStr(loan, "617");
                nameValueCollection.Add("617", str82);
                string str83 = JS.GetStr(loan, "101");
                nameValueCollection.Add("101", str83);
                string str84 = JS.GetStr(loan, "1145");
                nameValueCollection.Add("1145", str84);
                string str85 = Jed.BF(String.Compare(JS.GetStr(loan, "1374"), "", false) != 0, JS.GetStr(loan, "1374"), "");
                nameValueCollection.Add("1374_CoMorts", str85);
                string str86 = Jed.BF(String.Compare(JS.GetStr(loan, "1374"), "", false) != 0, "Co-Mortgagors", "");
                nameValueCollection.Add("CO_MORT", str86);
                string str87 = JS.GetStr(loan, "1169");
                nameValueCollection.Add("1169", str87);
                string str88 = JS.GetStr(loan, "1758");
                nameValueCollection.Add("1758", str88);
                string str89 = JS.GetStr(loan, "110");
                nameValueCollection.Add("110", str89);
                string str90 = JS.GetStr(loan, "1146");
                nameValueCollection.Add("1146", str90);
                string str91 = JS.GetStr(loan, "1759");
                nameValueCollection.Add("1759", str91);
                string str92 = JS.GetStr(loan, "273");
                nameValueCollection.Add("273", str92);
                string str93 = JS.GetStr(loan, "1168");
                nameValueCollection.Add("1168", str93);
                string str94 = Jed.BF(String.Compare(JS.GetStr(loan, "1374"), "", false) != 0, JS.GetStr(loan, "1374"), "");
                nameValueCollection.Add("1374", str94);
                string str95 = JS.GetStr(loan, "1171");
                nameValueCollection.Add("1171", str95);
                string str96 = JS.GetStr(loan, "1389");
                nameValueCollection.Add("1389", str96);
                string str97 = JS.GetStr(loan, "737");
                nameValueCollection.Add("737", str97);
                string str98 = JS.GetStr(loan, "1724");
                nameValueCollection.Add("128_465", str98);
                string str99 = JS.GetStr(loan, "1725");
                nameValueCollection.Add("129", str99);
                string str100 = JS.GetStr(loan, "1726");
                nameValueCollection.Add("130", str100);
                string str101 = JS.GetStr(loan, "1727");
                nameValueCollection.Add("131", str101);
                string str102 = JS.GetStr(loan, "1728");
                nameValueCollection.Add("132", str102);
                string str103 = JS.GetStr(loan, "1729");
                nameValueCollection.Add("133", str103);
                string str104 = JS.GetStr(loan, "1730");
                nameValueCollection.Add("134", str104);
                string str105 = Jed.BF(String.Compare(JS.GetStr(loan, "1379"), "", false) != 0, JS.GetStr(loan, "1379"), "");
                nameValueCollection.Add("1379", str105);
                string str106 = Jed.BF(String.Compare(JS.GetStr(loan, "1379"), "", false) != 0, "Co-Mtgs");
                nameValueCollection.Add("1379_CoMtgs", str106);
                string str107 = JS.GetStr(loan, "1731");
                nameValueCollection.Add("1731", str107);
                string str108 = Jed.BF(String.Compare(JS.GetStr(loan, "1384"), "", false) != 0, JS.GetStr(loan, "1384"), "");
                nameValueCollection.Add("1384", str108);
                string str109 = Jed.BF(String.Compare(JS.GetStr(loan, "1384"), "", false) != 0, "Co-Mtgs");
                nameValueCollection.Add("1384_CoMtgs", str109);
                string str110 = JS.GetStr(loan, "462");
                nameValueCollection.Add("462", str110);
                string str111 = JS.GetStr(loan, "1733");
                nameValueCollection.Add("970", str111);
                string str112 = JS.GetStr(loan, "1742");
                nameValueCollection.Add("1187", str112);
                string str113 = JS.GetStr(loan, "740");
                nameValueCollection.Add("740", str113);
                string str114 = JS.GetStr(loan, "742");
                nameValueCollection.Add("742", str114);
                string str115 = JS.GetStr(loan, "1539");
                nameValueCollection.Add("1539", str115);
                string str116 = JS.GetStr(loan, "353");
                nameValueCollection.Add("353", str116);
                string str117 = JS.GetStr(loan, "976");
                nameValueCollection.Add("976", str117);
                string str118 = JS.GetStr(loan, "1540");
                nameValueCollection.Add("1540", str118);
                string str119 = Jed.BF(String.Compare(JS.GetStr(loan, "1541"), "Exterior/Interior", false) == 0, "X");
                nameValueCollection.Add("1541_ExteriorInterior", str119);
                string str120 = Jed.BF(String.Compare(JS.GetStr(loan, "1541"), "Exterior Only", false) == 0, "X");
                nameValueCollection.Add("1541_ExteriorOnly", str120);
                string str121 = Jed.BF(String.Compare(JS.GetStr(loan, "1541"), "No Appraisal", false) == 0, "X");
                nameValueCollection.Add("1541_NoAppraisal", str121);
                string str122 = JS.GetStr(loan, "1542");
                nameValueCollection.Add("1542", str122);
                string str123 = Jed.BF(String.Compare(JS.GetStr(loan, "1543"), "Manual Underwriting", false) == 0, "X");
                nameValueCollection.Add("1543_Manual", str123);
                string str124 = Jed.BF(String.Compare(JS.GetStr(loan, "1543"), "DU", false) == 0, "X");
                nameValueCollection.Add("1543_DU", str124);
                string str125 = Jed.BF(String.Compare(JS.GetStr(loan, "1543"), "LP", false) == 0, "X");
                nameValueCollection.Add("1543_LP", str125);
                string str126 = Jed.BF(String.Compare(JS.GetStr(loan, "1543"), "Other", false) == 0, "X");
                nameValueCollection.Add("1543_Other", str126);
                string str127 = Jed.BF(String.Compare(JS.GetStr(loan, "1543"), "DU", false) == 0 | String.Compare(JS.GetStr(loan, "1543"), "LP", false) == 0 | String.Compare(JS.GetStr(loan, "1543"), "Other", false) == 0, "X");
                nameValueCollection.Add("1543_AUS", str127);
                string str128 = JS.GetStr(loan, "1556");
                nameValueCollection.Add("1556", str128);
                string str129 = JS.GetStr(loan, "1544");
                nameValueCollection.Add("1544", str129);
                string str130 = JS.GetStr(loan, "DU.LP.ID");
                nameValueCollection.Add("DU_LP_ID", str130);
                string str131 = JS.GetStr(loan, "1545");
                nameValueCollection.Add("1545", str131);
                string str132 = JS.GetStr(loan, "VASUMM.X23");
                nameValueCollection.Add("1484", str132);
                string str133 = Jed.BF(String.Compare(JS.GetStr(loan, "1550"), "Y", false) == 0, "X");
                nameValueCollection.Add("1550_Yes", str133);
                string str134 = Jed.BF(String.Compare(JS.GetStr(loan, "1550"), "Y", false) != 0, "X");
                nameValueCollection.Add("1550_No", str134);
                string str135 = JS.GetStr(loan, "1546");
                nameValueCollection.Add("1546", str135);
                string str136 = JS.GetStr(loan, "1547");
                nameValueCollection.Add("1547", str136);
                string str137 = JS.GetStr(loan, "191");
                nameValueCollection.Add("191", str137);
                string str138 = JS.GetStr(loan, "1548");
                nameValueCollection.Add("1548", str138);
                string str139 = JS.GetStr(loan, "1549");
                nameValueCollection.Add("1549", str139);
                string str140 = Jed.BF(String.Compare(JS.GetStr(loan, "1551"), "Y", false) == 0, "X");
                nameValueCollection.Add("1551_Yes", str140);
                string str141 = Jed.BF(String.Compare(JS.GetStr(loan, "1551"), "Y", false) != 0, "X");
                nameValueCollection.Add("1551_No", str141);
                string str142 = Jed.BF(String.Compare(JS.GetStr(loan, "1552"), "Y", false) == 0, "X");
                nameValueCollection.Add("1552_Yes", str142);
                string str143 = Jed.BF(String.Compare(JS.GetStr(loan, "1552"), "Y", false) != 0, "X");
                nameValueCollection.Add("1552_No", str143);
                string str144 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "NoteRate", false) == 0, "X");
                nameValueCollection.Add("1086_NoteRate", str144);
                string str145 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "NoteRate", false) == 0, JS.GetStr(loan, "3"));
                nameValueCollection.Add("1014_NoteRate", str145);
                string str146 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Above", false) == 0, "X");
                nameValueCollection.Add("1086_AboveNote", str146);
                string str147 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Above", false) == 0, JS.GetStr(loan, "1014"));
                nameValueCollection.Add("1014_AboveNote", str147);
                string str148 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Above", false) == 0, JS.GetStr(loan, "1660"));
                nameValueCollection.Add("1660_AboveNote", str148);
                string str149 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Below", false) == 0, "X");
                nameValueCollection.Add("1086_BelowNote", str149);
                string str150 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Below", false) == 0, JS.GetStr(loan, "1014"));
                nameValueCollection.Add("1014_BelowNote", str150);
                string str151 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Below", false) == 0, JS.GetStr(loan, "1660"));
                nameValueCollection.Add("1660_BelowNote", str151);
                string str152 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "BoughtDownRate", false) == 0, "X");
                nameValueCollection.Add("1086_BuyDown", str152);
                string str153 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "BoughtDownRate", false) == 0, JS.GetStr(loan, "1660"));
                nameValueCollection.Add("1660_Buydown", str153);
                string str154 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Other", false) == 0, "X");
                nameValueCollection.Add("1086_Other", str154);
                string str155 = Jed.BF(String.Compare(JS.GetStr(loan, "1086"), "Other", false) == 0, JS.GetStr(loan, "1660"));
                nameValueCollection.Add("1660_Other", str155);
                string str156 = JS.GetStr(loan, "1216");
                nameValueCollection.Add("1216", str156);
                string str157 = JS.GetStr(loan, "1217");
                nameValueCollection.Add("1217", str157);
                string str158 = JS.GetStr(loan, "1218");
                nameValueCollection.Add("1218", str158);
                string str159 = JS.GetStr(loan, "1219");
                nameValueCollection.Add("1219", str159);
                string str160 = JS.GetStr(loan, "1220");
                nameValueCollection.Add("1220", str160);
                string str161 = JS.GetStr(loan, "1221");
                nameValueCollection.Add("1221", str161);
                string str162 = JS.GetStr(loan, "1222");
                nameValueCollection.Add("1222", str162);
                string str163 = JS.GetStr(loan, "1829");
                nameValueCollection.Add("1223", str163);
                string str164 = JS.GetStr(loan, "1301");
                nameValueCollection.Add("1301", str164);
                string str165 = JS.GetStr(loan, "1302");
                nameValueCollection.Add("1302", str165);
                string str166 = JS.GetStr(loan, "1304") + Jed.BF(String.Compare(JS.GetStr(loan, "1292"), "", false) != 0, ", ") + JS.GetStr(loan, "1292") + " " + JS.GetStr(loan, "1305");
                nameValueCollection.Add("1304_1292_1305", str166);
                string str167 = JS.GetStr(loan, "997");
                nameValueCollection.Add("997", str167);
                string str168 = JS.GetStr(loan, "364");
                nameValueCollection.Add("364", str168);
                string str169 = JS.GetStr(loan, "352");
                nameValueCollection.Add("352", str169);
                string str170 = JS.GetStr(loan, "996");
                nameValueCollection.Add("996", str170);
                string str171 = JS.GetStr(loan, "971");
                nameValueCollection.Add("971", str171);
                string str172 = JS.GetStr(loan, "1303");
                nameValueCollection.Add("1303", str172);
                string str173 = JS.GetStr(loan, "1143");
                nameValueCollection.Add("1143", str173);
                string str174 = JS.GetStr(loan, "1293");
                nameValueCollection.Add("1293", str174);
                string str175 = Jed.BF(String.Compare(JS.GetStr(loan, "987"), "Standard", false) == 0, "X");
                nameValueCollection.Add("987_Standard", str175);
                string str176 = Jed.BF(String.Compare(JS.GetStr(loan, "987"), "Negotiated", false) == 0, "X");
                nameValueCollection.Add("987_Negotiated", str176);
                string str177 = JS.GetStr(loan, "TSUM.X4");
                nameValueCollection.Add("TSUMX4", str177);
                string str178 = JS.GetStr(loan, "38");
                nameValueCollection.Add("38", str178);
                string str179 = JS.GetStr(loan, "70");
                nameValueCollection.Add("70", str179);
                string str180 = Jed.BF(String.Compare(JS.GetStr(loan, "934"), "Y", false) == 0, "X");
                nameValueCollection.Add("934_Yes", str180);
                string str181 = Jed.BF(String.Compare(JS.GetStr(loan, "934"), "N", false) == 0, "X");
                nameValueCollection.Add("934_No", str181);
                return nameValueCollection;
            }
    }
    


}

    

