//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprovalsPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApprovalsPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] @__capprovalLetter {
            get {
                object obj = ResourceManager.GetObject("__capprovalLetter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1470693069_print_printer {
            get {
                object obj = ResourceManager.GetObject("_1470693069_print_printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _ctcLetter {
            get {
                object obj = ResourceManager.GetObject("_ctcLetter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _suspendedLetter {
            get {
                object obj = ResourceManager.GetObject("_suspendedLetter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;
        ///    Hi &lt;&lt;M_Loan_Pro&gt;&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    The loan for &lt;strong&gt;&lt;&lt;M_37&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;&lt;strong&gt;&lt;&lt;M_36&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;has been conditionally approved. Your approval letter is
        ///    attached to this email. For questions on this approval please contact underwriting support at 734-585-1500 option 4.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Thanks for your business!
        ///&lt;/p&gt;
        ///&lt;table border=&quot;1&quot; cellspacing=&quot;0&quot; cellpadding=&quot;3&quot; style=&quot;border-top-color:gold; border-top-width:thick&quot; &gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr &gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cdlAppBody {
            get {
                return ResourceManager.GetString("cdlAppBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;
        ///    Hi &lt;&lt;M_Loan_Pro&gt;&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    The loan for &lt;strong&gt;&lt;&lt;M_37&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;&lt;strong&gt;&lt;&lt;M_36&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;has been cleared to close.  Your final approval letter is attached to this email.  For questions on this approval please contact underwriting support at 734-585-1500 option 4.  Thanks for your business!
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    
        ///&lt;/p&gt;
        ///
        ///&lt;table border=&quot;1&quot; cellspacing=&quot;0&quot; cellpadding=&quot;3&quot; style=&quot;border-top-color:gold; border-top-width:thick&quot; &gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ctcAppBody {
            get {
                return ResourceManager.GetString("ctcAppBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goldstaricon {
            get {
                object obj = ResourceManager.GetObject("goldstaricon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_icon {
            get {
                object obj = ResourceManager.GetObject("insert_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightbackground {
            get {
                object obj = ResourceManager.GetObject("lightbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightbackground1 {
            get {
                object obj = ResourceManager.GetObject("lightbackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newprinticon {
            get {
                object obj = ResourceManager.GetObject("newprinticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newprinticon2 {
            get {
                object obj = ResourceManager.GetObject("newprinticon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printicon {
            get {
                object obj = ResourceManager.GetObject("printicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_green_dark_icon {
            get {
                object obj = ResourceManager.GetObject("search_green_dark_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search1 {
            get {
                object obj = ResourceManager.GetObject("search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stripped1008___TSUM_P1 {
            get {
                object obj = ResourceManager.GetObject("Stripped1008___TSUM_P1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stripped1008___TSUM_P1_pdf {
            get {
                object obj = ResourceManager.GetObject("Stripped1008___TSUM_P1_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;
        ///    Hi &lt;&lt;M_Loan_Pro&gt;&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    The loan for &lt;strong&gt;&lt;&lt;M_37&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;&lt;strong&gt;&lt;&lt;M_36&gt;&gt;&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;has been suspended.  Based on the submitted information we were unable to render an underwriting decision on this loan.  A copy of the suspense letter outlining reasons why is attached to this email.  If you have any questions please contact underwriting support at 734-585-1500 ext. 4.  Thanks for your business!
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Thanks for your business!
        ///&lt;/p&gt;
        ///&lt;tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string suspendedAppBody {
            get {
                return ResourceManager.GetString("suspendedAppBody", resourceCulture);
            }
        }
    }
}
